dist: xenial

language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
